Repository dragonflyoss/console, pull requests merged in 2025-09, with the labels that each got.

#584 chore: hide seedPeer route and tab
  cypress/e2e/seed-peers/seed-peer.cy.ts.skip
  cypress/e2e/seed-peers/seed-peers.cy.ts.skip
  src/components/clusters/show.tsx
  src/layouts/main.tsx
Labels: enhancement

#588 docs(README): update community involvement section
  README.md
Labels: documentation

#589 fix: Use relative paths to fix build issues
  package.json
Labels: bug
